### ISSUE TITLE
Check python3

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [ettoreleandrotognoli/python-ami#22]
Verify python 3 compatibility
str, unicode... refactoring could have  broken  something like the sockets

**Comment by romkazor** [comment]
Confirm broken sockets

Traceback (most recent call last):
  File "./rtcp.py", line 444, in <module>
    f = client.login(**login)
  File "/usr/local/lib/python3.6/site-packages/asterisk/ami/client.py", line 290, in _login_wrapper
    return self._login(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/asterisk/ami/client.py", line 125, in login
    return self.send_action(LoginAction(username, secret), callback)
  File "/usr/local/lib/python3.6/site-packages/asterisk/ami/client.py", line 141, in send_action
    self.send(action)
  File "/usr/local/lib/python3.6/site-packages/asterisk/ami/client.py", line 145, in send
    self._socket.send(bytearray(unicode(pack) + '\r\n', self.encoding))
NameError: name 'unicode' is not defined
